# Generated by Django 6.0.6 on 2026-07-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_address_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
