# Generated by Django 6.0.6 on 2026-07-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
