# Generated by Django 6.0.6 on 2026-07-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_failure_reason_payment_gateway_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
