# Generated by Django 6.0.6 on 2026-07-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_until',
            new_name='valid_to',
        ),
    ]
