# Generated by Django 6.0.6 on 2026-07-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_valid_until_coupon_valid_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_one_time_per_user',
            new_name='usage_per_user',
        ),
    ]
